REM INSERTING into CA_CONDITIONMAPPING
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (1,5,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (2,6,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (4,6,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (3,7,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (5,7,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (50,76,31);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (51,77,31);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (52,34,32);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (53,36,33);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (54,38,34);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (55,27,35);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (56,40,36);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (57,42,37);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (58,42,38);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (59,43,39);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (60,47,40);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (61,47,41);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (62,49,42);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (63,50,43);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (64,52,40);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (65,52,44);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (66,53,42);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (67,54,45);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (68,55,46);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (69,56,47);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (70,31,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (71,32,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (72,33,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (73,34,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (74,35,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (75,36,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (76,37,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (77,38,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (78,31,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (79,32,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (80,33,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (81,34,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (82,35,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (83,32,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (84,33,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (85,34,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (86,35,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (87,38,12);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (88,39,13);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (89,37,14);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (28,19,18);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (29,20,19);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (30,21,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (31,21,19);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (32,21,20);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (33,22,21);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (34,22,22);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (35,23,23);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (36,24,21);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (37,24,24);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (38,25,25);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (39,26,26);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (40,26,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (41,23,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (42,24,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (43,25,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (44,26,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (45,27,6);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (46,28,6);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (47,29,6);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (48,28,7);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (49,29,7);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (6,8,3);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (7,9,3);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (8,10,3);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (9,11,3);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (10,12,3);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (11,13,3);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (12,14,3);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (13,15,3);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (14,11,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (15,12,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (16,13,1);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (17,14,1);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (18,15,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (19,16,4);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (20,17,4);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (21,18,4);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (22,12,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (23,13,2);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (24,14,2);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (25,15,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (26,17,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (27,18,2);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (90,40,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (91,41,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (92,42,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (93,43,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (94,44,16);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (95,45,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (96,46,16);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (97,47,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (98,48,16);*/
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (99,40,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (101,41,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (102,42,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (103,43,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (104,44,27);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (105,45,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (106,46,27);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (107,47,27);*/
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (108,40,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (109,41,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (110,42,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (111,43,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (112,44,1);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (113,46,14);
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (114,47,12);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (115,48,13);*/
/*Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (116,49,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (117,50,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (118,51,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (119,52,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (120,53,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (121,54,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (122,55,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (123,56,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (124,57,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (125,58,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (126,49,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (127,50,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (128,51,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (129,52,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (130,53,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (131,54,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (132,55,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (133,56,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (134,57,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (135,58,8);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (136,49,9);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (137,50,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (138,51,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (139,52,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (140,53,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (141,54,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (142,55,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (143,56,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (144,57,10);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (145,58,10);*/
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (146,50,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (147,51,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (148,52,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (149,53,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (150,54,1);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (151,51,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (152,52,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (153,53,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (154,54,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (155,56,14);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (156,57,12);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (157,58,13);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (158,41,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (159,42,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (160,43,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (161,44,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (162,50,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (163,51,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (164,52,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (165,53,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (166,54,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (167,55,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (168,56,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (169,57,27);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (170,61,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (171,62,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (172,63,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (173,64,2);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (174,65,11);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (175,66,14);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (176,67,13);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (177,70,16);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (178,70,28);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (179,72,17);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (180,73,29);
Insert into CA_CONDITIONMAPPING (CACM_ID,CACM_SCENARIO_ID,CACM_CONDITION_ID) 
values (181,75,30);
